#5、Gitment
gitment_owner: EAPIAC       #你的 GitHub ID
gitment_repo: 'https://eapiac.github.io/index.html'          #存储评论的 repo
gitment_oauth:
  client_id: '373699ea1d7ef301488b'           #client ID
  client_secret: '6f94b2bdc349fee798640e0cc9d3607f88a48630'       #client secret
