#5、Gitment
gitment_owner: EAPIAC       #你的 GitHub ID
gitment_repo: 'EAPIAC.github.io'          #存储评论的 repo
gitment_oauth:
  client_id: '84dd1ecc6e41c471c61e'           #client ID
  client_secret: '5b4243d1a03e47809918a0de2c74a0145720442d'       #client secret
