#5、Gitment
gitment_owner: EAPIAC       #你的 GitHub ID
gitment_repo: 'EAPIAC.github.io'          #存储评论的 repo
gitment_oauth:
  client_id: '12af372b787ecae2b484'           #client ID
  client_secret: '393959b4499aff70a163670ea8fbf349cd0f40fc'       #client secret
