#5、Gitment
gitment_owner: EAPIAC       #你的 GitHub ID
gitment_repo: 'EAPIAC.github.io'          #存储评论的 repo
gitment_oauth:
  client_id: '85830c077d04d4963894'           #client ID
  client_secret: '824fc4cfbab748e5d94d2d915b2d2844df0f4a36'       #client secret
