#5、Gitment
gitment_owner: EAPIAC       #你的 GitHub ID
gitment_repo: 'EAPIAC.github.io'          #存储评论的 repo
gitment_oauth:
  client_id: '95894c97e800d57c4dfe'           #client ID
  client_secret: '7c80ad421508f970726a96f5ff09a760c734b36d'       #client secret
