#5、Gitment
gitment_owner:'EAPIAC'       #你的 GitHub ID
gitment_repo: 'EAPIAC.github.io'          #存储评论的 repo
gitment_oauth:
  client_id: 'e1f03307f28874713c00'           #client ID
  client_secret: '5be0a461c3fd14081f29ee970aff896b2a162c19'       #client secret
