#5、Gitment
gitment_owner: 'EAPIAC'      #你的 GitHub ID
gitment_repo: 'EAPIAC.github.io'          #存储评论的 repo
gitment_oauth:
  client_id: 'b1a8b57ecc0bfbd3c684'           #client ID
  client_secret: '399da802f38c3043577795afbea49b6a62c083ed'       #client secret
