#5、Gitment
gitment_owner:'EAPIAC'       #你的 GitHub ID
gitment_repo: 'EAPIAC.github.io'          #存储评论的 repo
gitment_oauth:
  client_id: 'ee2728abd19e88324ec4'           #client ID
  client_secret: '1aa05b1dbf4523579974a097e95f09025c4ce1b2'       #client secret
