#5、Gitment
gitment_owner: EAPIAC       #你的 GitHub ID
gitment_repo: 'EAPIAC.github.io'          #存储评论的 repo
gitment_oauth:
  client_id: '2fd6433db2b671fc26e0'           #client ID
  client_secret: '6280420ea9032490a163b923c06a191ee77e9f9b'       #client secret
